---
- name: Install Standard Utility Apps
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - curl
    - git
    - jq
    - ncal
    - unzip

- name: Ensure bin directory exists
  ansible.builtin.file:
    dest: "{{ home }}/bin"
    mode: 0700
    state: directory

- name: "Install Lazygit {{ lazygit_version }}"
  ansible.builtin.unarchive:
    src: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
    dest: "{{ home }}/bin/"
    remote_src: true

- name: Ensure .config directory exists
  ansible.builtin.file:
    dest: "{{ home }}/.config"
    mode: 0700
    state: directory

- name: Ensure Lazygit config directory is removed
  ansible.builtin.file:
    path: "{{ home }}/.config/lazygit"
    state: absent

- name: Link Lazygit Config
  ansible.builtin.file:
    src: "{{ setup_dir }}/dotfiles/lazygit"
    dest: "{{ home }}/.config/lazygit"
    state: link
