---
- name: Linux Desktop Setup
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - group_vars/secret-vars.yml

  roles:

    - role: core-apps
      tags:
        - core

    - role: desktop-apps
      tags:
        - apps

    - role: neovim
      tags:
        - nvim
        - apps

    - role: ssh
      tags:
        - config

    - role: git-config
      tags:
        - config

    - role: bash-aliases
      tags:
        - config

    - role: oh-my-posh
      tags:
        - config

    - role: global-scripts
      tags:
        - config
        - globalScripts

    - role: nodejs
      vars:
        node_version: "20.12.0"
      tags:
        - nodejs

    - role: dotnet
      tags:
        - dotnet

    - role: ansible-role-golang
      tags:
        - go

