#!/usr/bin/env bash
set -uo pipefail
sudo -v


# Variables.
export FREECAD_VER=1.0.2
export GHOSTTY_VER=1.2.3
export GOLANG_VER=1.25.4
export JET_BRAINS_VERSION=3.4.0
export NEOVIM_VERSION=0.11.4
export NODE_VERSION=22.14.0
export NVM_VERSION=0.40.3
export OBSIDIAN_VER=1.10.6
export SOURCE_REPO=git@github.com:JonGanz/dot-files.git


# Check OS.
if [[ -r /etc/os-release ]]; then
    . /etc/os-release
    export OS="$ID"

    if grep -qi microsoft /proc/version; then
        # WSL2 probably...
        export HAS_DE=0
    else
        export HAS_DE=1
    fi
else
    echo "Cannot detect OS"
    exit 1
fi


export APPIMAGE_DIR="$HOME/.appimage"
export OPEN_SOURCE_DIR="$HOME/.repos"
export SETUP_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

source "$SETUP_DIR/bash/ensure.sh"

ensure_directory "$APPIMAGE_DIR"
ensure_directory "$HOME/.config"
ensure_directory "$OPEN_SOURCE_DIR"


# Ensure configuration step completed.
if [[ ! -f "$SETUP_DIR/.env" ]]; then
    . "$SETUP_DIR/configure"
fi


# Bring in environment file.
set -a
. "$SETUP_DIR/.env"
set +a


# SSH Key setup will be outside the general scripts as it is interactive.
. "$SETUP_DIR/scripts/ssh.setup.sh"


# Output formatting.
skipped="\e[33m\u25CB Skipped\e[0m"
partial="\e[33m\u25CB Unknown progress\e[0m"
success="\e[32m✓ Success\e[0m"
failure="\e[31m✗ Failure\e[0m"


scripts=()

# core
scripts+=( \
    "suite.core.sh" \
    "git.sh" \
)

# package management
scripts+=( \
    "flatpak.sh" \
    "yay.sh" \
)

# SDKs
scripts+=( \
    "golang.sh" \
    "nodejs.sh" \
    "rust.sh" \
)

# terminal/dev tools
scripts+=( \
    "docker.sh" \
    "lazygit.sh" \
    "neovim.sh" \
    "oh-my-posh.sh" \
    "yazi.sh" \
)

# desktop applications
scripts+=( \
    "suite.multimedia.sh" \
    "brave.sh" \
    "ghostty.sh" \
    "jellyfin.sh" \
    "nextcloud-desktop.sh" \
    "web-apps.sh" \
    "steam.sh" \
    "spotify.sh" \
    "obsidian.sh" \
    "cad.sh" \
    "discord.sh" \
    "blender.sh" \
)

# desktop environment
scripts+=( \
    "fonts.sh" \
)


for script in "${scripts[@]}"; do
    echo -n "Running $script... "

    if command -v bc >/dev/null 2>&1; then
        USE_BC_TIME_MATH=1
    fi

    # Run the script and time it.
    child_out=$(mktemp "/tmp/setup-$script.XXX")
    timing=$( { time "./scripts/installs/$script" >"$child_out" 2>&1; } 2>&1 )
    result=$?
    real_time=$(echo "$timing" | head -n 2)
    minutes=$(echo "$real_time" | awk '{print $2}' | sed 's/m.*//')
    minutes="${minutes//$'\n'/}"
    seconds=$(echo "$real_time" | awk '{print $2}' | sed 's/.*m//; s/s//')
    seconds="${seconds//$'\n'/}"

    if [[ "${USE_BC_TIME_MATH:-0}" == "1" ]]; then
        run_time=$(echo "$minutes*60 + $seconds" | bc)
    else
        # TODO: Need to extract the decimal portion of the seconds since this only works for integer values.
        run_time=$(( minutes * 60 + seconds ))
    fi

    if [[ "$result" == "0" ]]; then
        echo -en "$success "
        printf "(%s seconds)\n" "$run_time"
    elif [[ "$result" == "1" ]]; then
        echo -en "$failure "
        printf "(%s seconds)\n" "$run_time"
        echo -e "\e[31mSee $child_out for more details\e[0m"
        exit 1
    elif [[ "$result" == "2" ]]; then
        echo -en "$skipped "
        printf "(%s seconds)" "$run_time"
        echo -e " - \e[33mSee $child_out for more details\e[0m"
    else
        echo -en "$partial "
        printf "(%s seconds)\n" "$run_time"
        echo -e "\e[33mSee $child_out for more details\e[0m"
    fi
done


# Add paths to PATH variable.
ensure_block_in_file "$HOME/.bashrc" "Initialize PATH" "$(cat <<EOF
export PATH=\$PATH:$HOME/.local/bin
export PATH=\$PATH:$HOME/bin
EOF
)"


# Setup bash aliases.
ensure_block_in_file "$HOME/.bashrc" "Use Bash Aliases" "$(cat <<-EOF
if [[ -f "$SETUP_DIR/dotfiles/bash_aliases" ]]; then
    . "$SETUP_DIR/dotfiles/bash_aliases"
fi
EOF
)"


# Switch the repo over to the SSH path.
pushd "$SETUP_DIR" > /dev/null
git remote set-url origin "$SOURCE_REPO"
popd > /dev/null


# All done.
exit 0


# -----------------------------------------------------------------------








# Install applications via `pacman`.
echo "Installing applications via pacman... "
echo -en "\033[1;30m"
sudo pacman -S --noconfirm --needed \
    gurk \
    ttf-jetbrains-mono-nerd \
&& echo -en "\033[0m"


# Setup Hyprland config.
ensure_symlink_dir "$SETUP_DIR/dotfiles/hypr" "$HOME/.config/hypr"


# TODO: Get some pimpin' backgrounds to match things.
# TODO: Replace rofi menu with something way nicer than that... or at least configure it to lot look like ass.
# TODO: Get a way to get audio control working..? Ha, this should probably be higher on the list, but who needs priorities?
# TODO: If no SSH key setup, guide through creation, and at the end inform the user how to add it to the Github account.

