---
- name: WSL Setup
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - group_vars/secret-vars.yml

  roles:

    - role: core-apps
      tags:
        - core

    - role: nodejs
      tags:
        - core

    - role: neovim
      tags:
        - nvim

    - role: ssh
      tags:
        - config

    - role: git-config
      tags:
        - config

    - role: bash-aliases
      tags:
        - bash

    - role: oh-my-posh
      tags:
        - config

    - role: global-scripts
      tags:
        - bash

    - role: dotnet
      tags:
        - core

    - role: ansible-role-golang
      tags:
        - go

  tasks:

    - name: Include SSH keychain setup
      include_role:
        name: ssh
        tasks_from: ssh-keychain.yml

