---
- name: WSL Setup
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - group_vars/secret-vars.yml
  roles:
    - core-apps
    - neovim
    - ssh
    - git-config
    - bash-aliases

