---
- name: WSL Setup
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - group_vars/secret-vars.yml
  roles:
    - role: core-apps
    - role: nodejs
      vars:
        node_version: "20.12.0"
    - role: neovim
    - role: ssh
    - role: git-config
    - role: bash-aliases
    - role: oh-my-posh
    - role: global-scripts

