---
- name: Ensure ssh-agent startup and add keys in .profile
  ansible.builtin.blockinfile:
    path: "{{ home }}/.profile"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED SSH AGENT BLOCK"
    block: |
      env=~/.ssh/agent.env

      agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

      agent_start () {
        (umask 077; ssh-agent >| "$env")
        . "$env" >| /dev/null ; }

      agent_load_env

      agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

      if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
        agent_start
        ssh-add
      elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
        ssh-add
        for key in {% for k in ssh_keys %} "{{ home }}/.ssh/id_rsa_{{ k.name }}" {% endfor %}; do
          if ! ssh-add -l | grep -q "$key"; then
            ssh-add "$key" >/dev/null 2>&1
          fi
        done
      fi

      unset env
