---
- name: Ensure bin directory exists
  ansible.builtin.file:
    dest: "{{ home }}/bin"
    mode: '0755'
    state: directory

- name: Copy scripts to bin directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/bin/"
    mode: '0755'
  with_fileglob:
    - "{{ role_path }}/files/*"

